config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :users do
	  resources :hostels
  end

  resources :hostels do
  	resources :bookings
  end

  resources :bookings,  :only => [] do
		get 'confirm_booking', on: :member

	end

  resources :users, :only => [] do
    resources :bookings, only: [:index]
  end

  get 'check_booking_availability', to: "bookings#check_booking_availability", as: :check_booking_availability
	
  get 'admin_booking_status', to: "bookings#admin_booking_status"
  get 'booking_checkout', to: "bookings#booking_checkout"
  get 'cancel_url', to: "bookings#cancel_url"
  get 'ipn_url', to: "bookings#ipn_url"
  get 'return_url', to: "bookings#return_url"
  get '/users/:id/subscription_index', to: "bookings#subscription_index", as: :users_subscriptions
  #patch 'bookings/:id/confirm_booking' , to: "bookings#confirm_booking", as: :update_booking

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
	after_create :send_email_to_admin, :send_email_to_user
	belongs_to :user
	belongs_to :hostel
	belongs_to :subscription 
	validates :no_of_rooms,numericality: true, presence: true
	validates :start_date, :end_date, presence: true
  def send_email_to_admin
 	  @hostel_user = User.find(hostel.user_id)
 	  UserMailer.booking_email_admin(@hostel_user).deliver
  end

  def send_email_to_user
    UserMailer.welcome_booking_email(user).deliver
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	 load_and_authorize_resource :except => [:subscription_index]
	def index
		#@hostel = Hostel.find(params[:hostel_id])
		@booking = current_user.bookings.order(created_at: :desc)
	end

	def new
	end

	def create                 
		@hostel = Hostel.find(params[:hostel_id])
		@booking = @hostel.bookings.new(booking_params)
		booking_room = booking_params[:no_of_rooms].to_i
		booked = Booking.where(hostel_id: @hostel).sum(:no_of_rooms)
		available_rooms = @hostel.no_of_rooms - booked
		if available_rooms >= booking_room
			@booking.save 
		else
			redirect_to :back, :alert => '* Number of rooms you want to book are not available'
		end
		@booked = Booking.where(hostel_id: @hostel).sum(:no_of_rooms)
		@hostel.available_rooms = @hostel.no_of_rooms - @booked
		@hostel.save
	end

	def show
		@hostel = Hostel.find(params[:hostel_id])
	end

	def confirm_booking
		@booking = Booking.find(params[:id])
		if @booking.update(confirm: true)
			UserMailer.welcome_booking_email(current_user).deliver
		end
		redirect_to root_path
	end

	def destroy
		hostel= Hostel.find(@booking.hostel_id)
		@booking.destroy
		booked = Booking.where(hostel_id: @booking.hostel_id).sum(:no_of_rooms)
		hostel.available_rooms = hostel.no_of_rooms - booked
		hostel.save
		redirect_to :back
	end

	def check_booking_availability
		@hostel = Hostel.find(params[:hostel_id])
		@booked = Booking.where(hostel_id: @hostel).sum(:no_of_rooms)
		@hostel_available_rooms = @hostel.no_of_rooms - @booked
		@Booking_room = params[:no_of_rooms]
		render json: [@hostel_available_rooms,@Booking_room]
	end

	def admin_booking_status
		@hostels = current_user.hostels
		#@user = Hostel.find(id: @hostel).user_id
	end

	def booking_checkout
		hostel = Hostel.find(params[:booking][:hostel_id])
		session[:hostel_id] = hostel.id
		paypal_id = User.find(hostel.user_id).paypal_email
		rooms = params[:booking][:no_of_rooms].to_i
		session[:rooms] = rooms
		start_date = params[:booking][:start_date]
		session[:start_date] = start_date
		end_date = params[:booking][:end_date]
		session[:end_date] = end_date
		amount = hostel.room_rent * rooms
		# @transaction = Transaction.new
		@api = PayPal::SDK::AdaptivePayments.new
		@pay = @api.build_pay({
		  :actionType => "PAY",
		  :cancelUrl => "http://localhost:3000/cancel_url",
		  :currencyCode => "USD",
		  :feesPayer => "SENDER",
		  :ipnNotificationUrl => "http://localhost:3000/ipn_url",
		  :receiverList => {
		    :receiver => [{
		      :amount => amount,
		      :email => "hmatre-facilitator@bestpeers.com" }] },
		  :returnUrl => "http://localhost:3000/return_url" })

		@response = @api.pay(@pay)
		if @response.success? && @response.payment_exec_status != "ERROR"
		  @response.payKey
		  session[:booking_paykey] = @response.payKey
		  @transaction = Transaction.new
		  redirect_to @api.payment_url(@response)  # Url to complete payment
		  # redirect_to hostels_path
		else
		  @response.error[0].message
		  redirect_to root_path
		end
	end

	def cancel_url
		@api = PayPal::SDK::AdaptivePayments::API.new
		# Build request object
	  @payment_details = @api.build_payment_details({:payKey => session[:booking_paykey] })
	  # Make API call & get response
	  payment_details_response = @api.payment_details(@payment_details)
	  @transaction_amount = payment_details_response.paymentInfoList.paymentInfo.first.receiver.amount
	  @time = payment_details_response.responseEnvelope.timestamp
		session[:booking_paykey] = nil
	end

	def ipn_url
	end

	def return_url
		@api = PayPal::SDK::AdaptivePayments::API.new
		# Build request object
	  @payment_details = @api.build_payment_details({:payKey => session[:booking_paykey] })
	  # Make API call & get response
	  payment_details_response = @api.payment_details(@payment_details)
	  transaction_id = payment_details_response.paymentInfoList.paymentInfo.first.transactionId
	  transaction_status = payment_details_response.paymentInfoList.paymentInfo.first.transactionStatus
		amount = payment_details_response.paymentInfoList.paymentInfo.first.receiver.amount
		receiver_pay_email = payment_details_response.paymentInfoList.paymentInfo.first.receiver.email
		paykey = payment_details_response.payKey
		@sender_pay_email = payment_details_response.sender.email
		
		if transaction_status == "COMPLETED"
			create_booking
		else
			redirect_to root_path, :alert => "* Sorry, due to some network issues transaction not completed"
		end

		create_transaction(amount, receiver_pay_email, @hostel.user_id, transaction_status, paykey, transaction_id )
		create_subscription(@transaction.id)
		
		session[:rooms] = nil
		session[:start_date] = nil
		session[:end_date] = nil
		session[:hostel_id] = nil
		session[:booking_paykey] = nil
	end
	
	def create_booking
		@booking = Booking.new({:no_of_rooms => session[:rooms], :start_date => session[:start_date], :end_date => session[:end_date], :user_id => current_user.id, :hostel_id => session[:hostel_id]})
		@booking.save
		
		@hostel = Hostel.find(session[:hostel_id])
		@booked = Booking.where(:hostel_id => session[:hostel_id]).sum(:no_of_rooms)
		@hostel.available_rooms = @hostel.no_of_rooms - @booked
		@hostel.save
	end

	def create_transaction(amount, receiver_pay_email, owner_id, transaction_status, paykey, transaction_id)
		@transaction = Transaction.new({:amount => amount, :user_id => current_user.id, :paypal_email => receiver_pay_email, :owner_id => owner_id, :paypal_status => transaction_status, :paypal_paykey => paykey, :paypal_transaction_id => transaction_id })
		@transaction.save
	end

	def create_subscription(t_id)
		@subscription = Subscription.new({:user_id => current_user.id, :transaction_id => t_id, :start_date => session[:start_date], :end_date => session[:end_date] })
		@subscription.save
		sub_id = @subscription.id
		booking_update = Booking.last
		booking_update.subscription_id = sub_id
		booking_update.save
	end

	def subscription_index
		@subscriptions = current_user.subscriptions
	end

	private
	
 	def booking_params
 	 params.require(:booking).permit(:start_date, :end_date, :no_of_rooms).merge({user_id:current_user.id})
 	end

 	
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_new.html.erb
<div class="row">
	<div class="col-sm-6">
		<%= form_for [@hostel, @booking], url: booking_checkout_path, method: 'GET' do |f| %>
			<% if @booking.errors.any? %>
			    <% @booking.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  <% end %>

			<div class="form-group">
			  <%= f.label :no_of_rooms, "No of Rooms" %><br />
			  <%= f.text_field :no_of_rooms, class: "form-control", autofocus: true, id: 'rooms' %></br>
			  <span id="show" style="color:red"></span>
			</div>

			<div class="form-group">
				 <%= f.label :start_date, "Select start date for booking" %><br />
				<div class='input-group date' id='start_datepicker'>
					<%= f.text_field :start_date, class: "form-control start_date", id: 'start_date' %>
				  <!-- <input type="text" class="form-control start_date" id="start_date"/> -->
				  <span class="input-group-addon start_date">
	        	<span class="glyphicon glyphicon-calendar"></span>
	      	</span>
      	</div>
			  <%#= f.date_field :start_date, class: "form-control", id: 'start-date' %>
			</div>

			<div class="form-group">
			  <%= f.label :end_date, "Select end date for booking" %><br />
			  <div class='input-group date' id='end_datepicker'>
			  	<%= f.text_field :end_date, class: "form-control end_date", id: 'end_date' %>
			  	<!-- <input type="text" class="form-control end_date"  id="end_date"/> -->
				  <span class="input-group-addon">
	        	<span class="glyphicon glyphicon-calendar"></span>
	      	</span>
	      </div>
	      <div class="row" style="color:red" id="error"></div>
			  <%#= f.date_field :end_date, class: "form-control", id: 'end-date' %>
			</div>

			<div class="form-group"><br />
				<%= f.hidden_field :hostel_id,:value => @hostel.id %>
			  <%= f.submit "Book",class: 'btn btn-primary', id: 'btn1' %>
			</div>
		
		<%#= link_to 'pay', booking_checkout_path %>
		<%end%>
	</div>
</div>

<script type="text/javascript">
	$('#rooms').keyup(function(){
		$.ajax({
		  method: "GET",
		  url: "<%= check_booking_availability_path %>",
		  data: {
		  	no_of_rooms: $(this).val(),
		  	hostel_id: <%= @hostel.id %>
		  },
		  success: function(data){
		  	// debugger
		  	if (data[0] < data[1]) {
		  		$('#show').html('only-' + data[0] + '-rooms available');
		  		$('#btn1').prop('disabled', true);
		  	}else{
		  		$('#show').html('');
		  		$('#btn1').prop('disabled', false);
		  	}
		  }
		});

		$('#showbooking').on('hidden.bs.modal', function () {
			$('#rooms').val('');
			$('#start-date').val('');
			$('#end-date').val('');
			$('#show').text('');
		});
	});

	$(document).ready(function(){
    $('#start_datepicker').datepicker({
    	format: "dd/mm/yyyy",
    	startDate: Date(),
    	autoclose: true
    });

    $('#end_datepicker').datepicker({
    	format: "dd/mm/yyyy",
    	startDate: Date(),
    	autoclose: true
    });
  });

	
  
 	$('#end_date').change(function(){
 		var start_date = $('#start_date').val();
    	var end_date = $('#end_date').val();
  	//alert("enter valid date");
  	//debugger
  	 if(start_date > end_date){
  	 	//alert("enter valid date");
  	 	$('#error').html('End date is not before the start date');
  	 }
  	 else{
  	 	$('#error').html('');
  	 }

  });

</script>

app/views/bookings/admin_booking_status.html.erb
<div class="container">
	<h1>Booking Details</h1>
	<table class="table table-hover col-md-5">
		<tr>
			<th>Hostel Name</th>
			<th>Total Number Rooms</th>
			<th>Rooms Booked</th>
			<th>Available Rooms</th>
		</tr>
		<tr>

			<% @hostels.each do |f| %>
				<td><%= f.name %></td>
				<td><%= f.no_of_rooms %></td>
				<%#byebug%>
				<td><%=  f.bookings.sum(:no_of_rooms) %></td>
				<% if f.available_rooms == nil %>
					<td><%= f.no_of_rooms %></td>
				<%else%>
					<td><%= f.available_rooms %></td>
				<%end%>
		</tr>
			<%end%>
	</table>
	<%= link_to 'Back', root_path,class: 'btn btn-info' %>
</div>

app/views/bookings/cancel_url.html.erb
<div class="row" style="color:red">
	<h3>You have cancel this transaction process.</h3>
</div>
<div>
		<h4>Transaction Failed</h4>
		<strong>Transaction amount : </strong><%= @transaction_amount %></br>
		<strong>Time : </strong><%= @time %></br>
</div>
<div class="row">
	<%= link_to 'back', root_path %>	
</div>

app/views/bookings/confirm_booking.html.erb
<div class="container">
	<%= Booking.last  %>
	<%= link_to 'confirm', confirm_booking_booking_path(Booking.last), method: :patch %>
</div>

app/views/bookings/create.js.erb
$('#available-rooms').html('<%= @hostel.available_rooms %>');
$('#rooms').val("");
$('#start-date').val('');
$('#end-date').val('');
//$('#showbooking').modal('hide');
var rooms = <%= @hostel.available_rooms %>
$('#showbooking').modal('hide').on('hidden.bs.modal', function () {
	//alert("hello");	
	if (rooms == 0) {
	$('#btn').text('Booking Full');
	$('#btn').attr('disabled', true);
	}
});

app/views/bookings/index.html.erb
<div class="container ">
	<h1>Booking Details</h1>
	<table class="table table-hover col-md-5">
		<tr>
			<th>Hostel Name</th>
			<th>Rooms Booked</th>
			<th>Booking From Date</th>
			<th>Booking To Date</th>
			<th>Option</th>
		</tr>
		<% if current_user.bookings.present? %>
			<% @booking.each do |f| %>
				<tr>
					<td><%= f.hostel.name %></td>
					<td><%= f.no_of_rooms %></td>
					<td><%= f.start_date.strftime('%F') %></td>
					<td><%= f.end_date.strftime('%F') %></td>
					<td><%= link_to 'delete', hostel_booking_path(current_user.id, f),class: 'btn btn-info', method: :delete, data: {confirm: "are u sure you want to cancel Booking?"} %></td>
				</tr>
			<%end%>
		<%else%>
			<tr><td>Currently you have no bookings</td></tr>
		<%end%>
	</table>
	<%= link_to "back", root_path,class: 'btn btn-info'  %>
</div>

app/views/bookings/return_url.html.erb
<div>
	<div class="row" style="color:green"><h4>Your Booking has been done Successfully.</h4></div>
	<div>
		<strong>Transaction id : </strong><%= @transaction.paypal_transaction_id %></br>
		<strong>To Pay Email : </strong><%= @transaction.paypal_email %></br>
		<strong>From Pay Email : </strong><%= @sender_pay_email %></br>
		<strong>Amount : </strong><%= @transaction.amount %></br>
		<strong>Pay Key : </strong><%= @transaction.paypal_paykey %></br>
		<strong>Transaction Status : </strong><%= @transaction.paypal_status %></br>
	</div>
	<%= link_to 'back', root_path %>
</div>

app/views/bookings/subscription_index.html.erb
<h2>Subscriptions Details</h2>
<div>
	<table class="table table-hover col-md-5">
		<tr>
			<th>Transaction Id</th>
			<th>Hostel Name</th>
			<th>No of Rooms Booked</th>
			<th>Booked From Date</th>
			<th>Booked To Date</th>
		</tr>

		<% if current_user.subscriptions.present? %>
		<% @subscriptions.each do |f| %>
			<tr>
				<td><%= f.transaction_id %></td>
				<%#byebug%>
				<td><%= f.booking.hostel.name %></td>
				<td><%= f.booking.no_of_rooms %></td>
				<td><%= f.start_date.strftime('%F') %></td>
				<td><%= f.end_date.strftime('%F') %></td>
		<%end%>
			</tr>
		<%else%>
		<tr><td>Currently you have no Subscriptions</td></tr>
		<%end%>
	</table>
	<%= link_to "back", root_path,class: 'btn btn-info'  %>
</div>