config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :users do
	  resources :hostels
  end

  resources :hostels do
  	resources :bookings
  end

  resources :bookings,  :only => [] do
		get 'confirm_booking', on: :member

	end

  resources :users, :only => [] do
    resources :bookings, only: [:index]
  end

  get 'check_booking_availability', to: "bookings#check_booking_availability", as: :check_booking_availability
	
  get 'admin_booking_status', to: "bookings#admin_booking_status"
  get 'booking_checkout', to: "bookings#booking_checkout"
  get 'cancel_url', to: "bookings#cancel_url"
  get 'ipn_url', to: "bookings#ipn_url"
  get 'return_url', to: "bookings#return_url"
  get '/users/:id/subscription_index', to: "bookings#subscription_index", as: :users_subscriptions
  #patch 'bookings/:id/confirm_booking' , to: "bookings#confirm_booking", as: :update_booking

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 align="center">Welcome to Hostel Management System</h1>
<div class="container">
	<div style="margin-bottom: 10px;">
		<% if user_signed_in? %>
			<ul class="nav nav-pills">
				<li><%= link_to 'See All Hostels List', hostels_path, class: 'btn btn-info' %></li>
				
				<li><%= link_to 'Subscriptions', users_subscriptions_path(current_user.id), class: 'btn btn-info' %></li>
				
				<%# if current_user.bookings.present? %>
					<li><%= link_to 'See All Your Booking', user_bookings_path(current_user), class: 'btn btn-info' %></li>
				<%#end%>
				
				<% if current_user.admin? %>
					<li><%= link_to 'Hostel Bookings status', admin_booking_status_path, class: 'btn btn-info' %></li>
				<%end%>
			</ul>
		<%end%>
	</div>	

	<div class="row" >
		<% Hostel.first(3).each do |f| %>
			<div class="col-md-4">
				<%= image_tag(f.image_url, class: 'img img-responsive', style: "max-height:240px;" ) %>
				<strong><p class="text-center text-uppercase"><%= f.name %></p></strong>
			</div>	
		<%end%>
	</div>

	<div style="margin-top: 20px;">
		<p>
			Hostel Management System monitors and records a variety of information covering Hostel Attendance, Disciplinary Logs, as well as Room charge Status.
		
			Hostel software module includes many features like fee collection, room allotment, room management as categorization of rooms, daily attendance register of hostel and hostel reports.
		
			Hostel management system module includes many reports like room allotment register, room left report, charge due reports and receipts, room transfer register and room status report.
		</p>
	</div>
	
</div>