config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :users do
	  resources :hostels
  end

  resources :hostels do
  	resources :bookings
  end

  resources :bookings,  :only => [] do
		get 'confirm_booking', on: :member

	end

  resources :users, :only => [] do
    resources :bookings, only: [:index]
  end

  get 'check_booking_availability', to: "bookings#check_booking_availability", as: :check_booking_availability
	
  get 'admin_booking_status', to: "bookings#admin_booking_status"
  get 'booking_checkout', to: "bookings#booking_checkout"
  get 'cancel_url', to: "bookings#cancel_url"
  get 'ipn_url', to: "bookings#ipn_url"
  get 'return_url', to: "bookings#return_url"
  get '/users/:id/subscription_index', to: "bookings#subscription_index", as: :users_subscriptions
  #patch 'bookings/:id/confirm_booking' , to: "bookings#confirm_booking", as: :update_booking

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hostel.rb
class Hostel < ApplicationRecord
	mount_uploader :image, AvatarUploader
	validates :name, :no_of_rooms, :room_rent, presence: true
	validates :address, presence: true
	validates :pincode, length:{is: 6}
	validates :mobile_number, length:{is: 10}
	
	belongs_to :user
	has_many :bookings
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
	load_and_authorize_resource except: [:index]

	def index
		if params[:q].present?
			@q = Hostel.search(name_cont: params[:q][:name])
			# @q = Hostel.search(params[:q])
		else
			@q = Hostel.search(params[:q])
		end
		@hostels = @q.result(distinct: true)
	end

	def new
	end

	def create
		@hostel = current_user.hostels.new(hostel_params)
		debugger
		if @hostel.save
			redirect_to user_hostels_path(current_user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @hostel.update(hostel_params)
			redirect_to user_hostels_path(current_user)
		else
			render 'edit'
		end
	end
	
	def show
		@booking= Booking.new
		@booked = Booking.where(hostel_id: @hostel).sum(:no_of_rooms)
		@hostel.available_rooms = @hostel.no_of_rooms - @booked
		# @booking = @hostel.bookings.find_by(user_id: current_user.id)
	end

	private
	def hostel_params
		params.require(:hostel).permit!
	end
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/views/hostels/_form.html.erb
<div class="row">
	<div class="col-md-3">
		<%= form_for ([current_user, @hostel] )do |f| %>
			<% if @hostel.errors.any? %>
			    <% @hostel.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			  <% end %>
			
			<div class="form-group">
			  <%= f.label :name, "Hostel Name" %><br />
			  <%= f.text_field :name, class: "form-control" , autofocus: true %>
			</div>

			<div class="form-group">
			  <%= f.label :description %><br />
			  <%= f.text_area :description, class: "form-control" %>
			</div>

			<div class="form-group">
			  <%= f.label :address %><br />
			  <%= f.text_field :address, class: "form-control"%>
			</div>

			<div class="form-group">
			  <%= f.label :pincode %><br />
			  <%= f.text_field :pincode, class: "form-control"%>
			</div>

			<div class="form-group">
			  <%= f.label :mobile_number %><br />
			  <%= f.text_field :mobile_number, class: "form-control"%>
			</div>

			<div class="form-group">
			  <%= f.label :no_of_rooms %><br />
			  <%= f.text_field :no_of_rooms, class: "form-control"%>
			</div>

			<div class="form-group">
			  <%= f.label :room_rent %><br />
			  <%= f.text_field :room_rent, class: "form-control"%>
			</div>

			<div class="form-group">
			  <%= f.label :image %><br />
			  <%= f.file_field :image, class: "form-control"%>
			</div>

			<div class="form-group"><br />
			  <%= f.submit "Submit", class: "btn btn-primary" %>
			</div>
		<%end%>
	</div>
</div>

app/views/hostels/edit.html.erb
<div class="container">
	<h1>Edit Hostel details</h1>
	<%= render "hostels/form" %>
	<%= link_to 'Back', root_path,class: 'btn btn-info' %>
</div>

app/views/hostels/index.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<%= search_form_for @q do |f| %>
		  <div class="form-group">
			 	<%= f.search_field :name, class: "form-control", placeholder: "Hostel Name", style: "width:80%; float:left;" %>
			 	<%= f.submit "Search", class: "btn btn-info" %>
		 	</div>
		<% end %>
	</div>
	<div class="col-md-3"></div>
</div>

<div class="container">
	<h1>List of Hostels</h1>
	<% if current_user.admin? %>
		<%= link_to 'Add new Hostel', new_user_hostel_path(current_user),class: 'btn btn-info' %>
	<%end%>
	<table class="table table-hover" style="margin-top: 15px;">	
		<tr>
			<th><%= sort_link(@q, :name, 'Hostel Name')%></th>
			<th colspan="2">Options</th>
		</tr>
		<tr>
			<% @hostels.each do |f| %>
				<td><%= f.name %></td>
				<td><%= link_to 'Show', hostel_path(f),class: 'btn btn-info' %></td>
		</tr>
			<%end%>
	</table>
  <%= link_to 'Back', root_path,class: 'btn btn-info' %>
</div>

app/views/hostels/new.html.erb
<div class="container">
	<h1>Add New Hostel</h1>
	<%= render "hostels/form" %>
	<%= link_to 'Back', root_path,class: 'btn btn-info' %>
</div>

app/views/hostels/show.html.erb
<div class="container">
	<h2>Hostel Details</h2>
	<div class="row" style="margin-bottom: 20px;">
		<div class="col-sm-6">
			<%= image_tag(@hostel.image_url, class: 'img img-responsive') %>
		</div>
		<div class="col-sm-6">
			<div class="col-sm-12">
				<% if @hostel.available_rooms>0 %>
					<button type="button" class="btn btn-info" data-toggle="modal" data-target="#showbooking" id="btn" style="float: right;">Click Here to Book Room</button>
					<% else %>
					<button type="button" class="btn btn-info" >Booking full</button>
				<%end%>
			</div>

			<h3 class="text-uppercase"><%= @hostel.name %></h3>
			<ul style="list-style-type: none; padding: 0;">
				<li>No of Rooms: <%= @hostel.no_of_rooms %></li>			
				<li>Room Rent: <%= @hostel.room_rent %></li>			
				<li id="available-rooms">Available Room: <%= @hostel.available_rooms %></li>
			</ul>
			<p><strong>Description:</strong></p>
			<p><%= @hostel.description %></p> 
		</div>
		<div class="col-sm-12" style="margin-top: 15px;">
			<strong>Contact Details:</strong>
			<ul style="list-style-type: none; padding-left: 10px;">
				<li><%= @hostel.address %></li>
				<li><%= @hostel.pincode %></li>
				<li><%= @hostel.mobile_number %></li>
			</ul>
		</div>		
	</div>
	
	<div class="row" style="margin-bottom: 20px;">
		<div class="col-sm-12">
			<% if current_user.admin? && current_user.id == @hostel.user_id %>
				<%= link_to 'Edit Hostel Details', edit_user_hostel_path(current_user, @hostel.id),class: 'btn btn-info' %> ||	
			<%end%>
			<%= link_to 'Back', hostels_path,class: 'btn btn-info' %>
		</div>
	</div>
	
</div>
<!-- <div class="container" align="center">
	<h4>Book Room</h4>
	<%#byebug%>
	<%#=button_to 'book', hostel_bookings_path(@hostel.id), :method => 'post' %>
</div> -->

<div id="showbooking" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Enter Details for Booking Rooms</h4>
      </div>
      <div class="modal-body">
        <%= render 'bookings/new' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default " data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>